# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tune_my_query}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Anuj Dutta"]
  s.date = %q{2009-12-16}
  s.description = %q{Switches between standard SQL and extended SQL syntax depending on the adapter.}
  s.email = %q{anuj@andhapp.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "HISTORY",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/tune_my_query.rb",
     "lib/tune_my_query/commands/LikeCommand.rb",
     "lib/tune_my_query/tune_my_query.rb",
     "pkg/tune_my_query-0.1.0.gem",
     "spec/database.yml",
     "spec/lib/tune_my_query_spec.rb",
     "spec/models.rb",
     "spec/schema.db",
     "spec/spec_helper.rb",
     "tune_my_query.gemspec"
  ]
  s.homepage = %q{http://github.com/andhapp/tune_my_query}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Standardises SQL syntax across databases.}
  s.test_files = [
    "spec/lib/tune_my_query_spec.rb",
     "spec/models.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
